### ISSUE TITLE
(4) Combat: Attacks, hit detection, and damage

### ISSUE THREAD

**Issue by murtaza64** [Amoriem-Labs/bulldog-bash#23]
This can mostly be already worked on, but Pax and Alex are working on building a health system (#34) that this ticket may rely on, so wait for that.

Update — that ticket has been done. Global health system has been created (e.g. global.left_player_health)

**Comment by Krishna2182** [comment]
Some tasks to do:
- Create collision masks for regular and attacking sprites
- Temporarily using RTYC for WASD player and NM<> for arrow key players
    - but <> keys aren't recognized right now
- Create attacked event from collision of attacked player collision mask with collision mask of attacking object
- Decrease health with attacks

**Comment by dsmaugy** [comment]
Some more notes:

Currently the attack button needs to be held down for the animation to fully go through. We should be able to fully go through the attack animation by pressing the key once. Probably implement this with the animation states
