### ISSUE TITLE
(1) Camera viewport & multiplayer zooming (16:9)

### ISSUE THREAD

**Issue by murtaza64** [Amoriem-Labs/bulldog-bash#26]

**Comment by christieyu** [comment]
When two characters are far apart, make the viewport bigger. Otherwise, make the viewport about 2.5x the height of the characters.

**Comment by JiheHe** [comment]
Basically finished basic-level zooming; needs to implement camera movement for characters in sky (Y-axis): do we want to move camera up or do small separate camera like Smash?
