### ISSUE TITLE
(2) Starting character select room, tied to UI in-game

### ISSUE THREAD

**Issue by christieyu** [Amoriem-Labs/bulldog-bash#54]
1) Create basic select room when game loads where you can select a character and map (in our case, only 2 characters and 1 map available). It would be good to show splash portraits and map thumbnail here.

2) Change the UI to reflect each person's character, character name, etc.

ALL ASSETS IN DROPBOX:
/Dropbox/Amoriem Labs/Bulldog Bash/final spritesheets/map & ui

**Comment by murtaza64** [comment]
This should be a new room that then switches to the combat room we have. Once this issue is implemented, round start from #64 can be triggered after character select, but all we need to do from this side of things is load the combat room
